"use client"
import '../../styles/globals.css'
import { Inter } from 'next/font/google';
import { useRouter } from 'next/navigation';
import NavBar from '@/src/components/NavBar/page';
import Footer from '@/src/components/footer/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter()
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
